<?php
/**
 * Cardea - Proof-of-Work Comment Spam Protection
 *
 * Copyright (C) 2024 Oleg Mikheev
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

/**
 * PHPUnit Bootstrap File
 *
 * @package Cardea
 */

define( 'ABSPATH', '/var/www/html/' );
define( 'CARDEA_PLUGIN_DIR', __DIR__ . '/../../' );
define( 'CARDEA_PLUGIN_URL', 'https://example.com/wp-content/plugins/cardea/' );
define( 'CARDEA_VERSION', '1.0.0' );
define( 'CARDEA_DEFAULT_DIFFICULTY', 4 );
define( 'CARDEA_DEFAULT_WINDOW', 30 );

require_once __DIR__ . '/../../vendor/autoload.php';

require_once CARDEA_PLUGIN_DIR . 'includes/class-cardea-core.php';

function get_option( $option, $default = false ) {
	global $wp_options;
	return $wp_options[ $option ] ?? $default;
}

function update_option( $option, $value ) {
	global $wp_options;
	$wp_options[ $option ] = $value;
	return true;
}

function wp_create_nonce( $action = -1 ) {
	return 'test_nonce_' . $action . '_' . time();
}

function set_transient( $transient, $value, $expiration = 0 ) {
	global $wp_transients;
	$wp_transients[ $transient ] = $value;
	return true;
}

function get_transient( $transient ) {
	global $wp_transients;
	return $wp_transients[ $transient ] ?? false;
}

function delete_transient( $transient ) {
	global $wp_transients;
	unset( $wp_transients[ $transient ] );
	return true;
}

class WP_Error {
	private $code;
	private $message;
	private $data;

	public function __construct( $code, $message = '', $data = '' ) {
		$this->code   = $code;
		$this->message = $message;
		$this->data    = $data;
	}

	public function get_error_code() {
		return $this->code;
	}

	public function get_error_message() {
		return $this->message;
	}

	public function get_error_data() {
		return $this->data;
	}

	public function __toString() {
		return $this->message;
	}
}

function is_wp_error( $thing ) {
	return $thing instanceof WP_Error;
}

function __( $text, $domain = 'default' ) {
	return $text;
}

function esc_html__( $text, $domain = 'default' ) {
	return esc_html( $text );
}

function _e( $text, $domain = 'default' ) {
	echo esc_html( $text );
}

function esc_html( $text ) {
	return htmlspecialchars( $text, ENT_QUOTES, 'UTF-8' );
}

function esc_attr( $text ) {
	return htmlspecialchars( $text, ENT_QUOTES, 'UTF-8' );
}

function sanitize_text_field( $str ) {
	return trim( strip_tags( $str ) );
}

function wp_unslash( $value ) {
	return is_array( $value ) ? array_map( 'wp_unslash', $value ) : stripslashes( $value );
}

function wp_die( $message = '', $title = '', $args = array() ) {
	throw new Exception( $message );
}

global $current_user;
$current_user = null;

function current_user_can( $capability, ...$args ) {
	global $current_user;
	if ( $current_user === null ) {
		return false;
	}
	if ( isset( $current_user->caps[ $capability ] ) ) {
		return (bool) $current_user->caps[ $capability ];
	}
	if ( isset( $current_user->allcaps[ $capability ] ) ) {
		return (bool) $current_user->allcaps[ $capability ];
	}
	return false;
}

function is_user_logged_in() {
	global $current_user;
	return $current_user !== null;
}

class WP_User {
	public $caps = array();
	public $allcaps = array();
	public $roles = array();

	public function __construct( $user_id = 0, $name = '', $email = '' ) {
		$this->caps = array();
		$this->allcaps = array();
	}
}

global $wp_filters;
$wp_filters = array();

function apply_filters( $tag, $value, ...$args ) {
	global $wp_filters;
	if ( isset( $wp_filters[ $tag ] ) ) {
		foreach ( $wp_filters[ $tag ] as $callback ) {
			$value = call_user_func_array( $callback, array_merge( array( $value ), $args ) );
		}
	}
	return $value;
}

function add_filter( $tag, $callback, $priority = 10, $accepted_args = 1 ) {
	global $wp_filters;
	if ( ! isset( $wp_filters[ $tag ] ) ) {
		$wp_filters[ $tag ] = array();
	}
	$wp_filters[ $tag ][] = $callback;
	return true;
}

function wp_verify_nonce( $nonce, $action = -1 ) {
	if ( empty( $nonce ) ) {
		return false;
	}
	// WordPress nonces are formatted as: hash/action/timestamp
	// For testing, we only accept nonces starting with 'test_nonce_' (generated by wp_create_nonce mock)
	// Any other format (like 'invalid_nonce' or 'random') should fail
	if ( strpos( $nonce, 'test_nonce_' ) === false ) {
		return false;
	}
	return true;
}

function wp_salt( $scheme = 'auth' ) {
	global $wp_salts;
	if ( isset( $wp_salts[ $scheme ] ) ) {
		return $wp_salts[ $scheme ];
	}
	return 'test_salt_' . $scheme;
}

global $wp_salts;
$wp_salts = array(
	'nonce' => 'test_nonce_salt_12345',
	'auth'  => 'test_auth_salt_67890',
	'secure' => 'test_secure_salt_abcde',
);

global $wp_options;
$wp_options = array();

global $wp_transients;
$wp_transients = array();
